version: "3"
services:
  web:
    container_name: WEB_API
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
  db:
    container_name: DATABASE
    image: postgres
    restart: always
    volumes:
      - ./database/db_init:/docker-entrypoint-initdb.d
      # NB: sudo rm -rf db_data folder to nuke DB
      - ./database/db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  db_data:
