version: "3.3"
services:
  api:
    container_name: METSCOPE_DEV_API
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node/app
  db:
    container_name: METSCOPE_LOCAL_DATABASE
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
