version: "3"
services:
  # To run API standalone:
  # docker-compose run --name METSCOPE-PROD -d --service-ports web
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  web:
    container_name: WEB_API
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
  db:
    container_name: DATABASE
    image: postgres
    restart: always
    volumes:
      - ./database/db_init:/docker-entrypoint-initdb.d
      # NB: sudo rm -rf db_data folder to nuke DB
      - ./database/db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  db_data:
