version: 2
jobs:
  build+test:
    docker:
      - image: circleci/node:10.0
    steps:
      - checkout
      - run:
          name: Identify branch
          command: |
            echo ${CIRCLE_BRANCH}

  deploy-staging:
    docker:
      - image: circleci/node:10.0
    steps:
      - run:
          name: Deploy staging branch to DigitalOcean Droplet
          command: |
            echo 'Deploying to staging environment'
            ssh -o "StrictHostKeyChecking no" ${DROPLET_USER}@${DROPLET_ADDRESS} 'cd /home/metscope/staging/metscope; ls -alh'

  deploy-production:
    docker:
      - image: circleci/node:10.0
    steps:
      - run:
          name: Ident
          command: |
            echo 'Deploying 'master' branch to production environment'

workflows:
  version: 2
  build+deploy:
    jobs:
      - build+test:
          filters:
            branches:
              only:
                - develop
                - staging
                - master

      - deploy-staging:
          requires:
            - build+test
          filters:
            branches:
              only: staging

      - deploy-production:
          requires:
            - build+test
          filters:
            branches:
              only: master
