version: 2
jobs:
  run-tests:
    docker:
      - image: circleci/node:10.0
    steps:
      - checkout
      - run:
          name: Identify branch
          command: |
            echo ${CIRCLE_BRANCH}

  deploy-to-staging-env:
    docker:
      - image: circleci/node:10.0
    steps:
      - run:
          name: Deploy staging branch to DigitalOcean Droplet
          command: |
            echo 'Deploying to staging environment'
            ssh -o "StrictHostKeyChecking no" ${DROPLET_USER}@${DROPLET_ADDRESS} 'cd /home/metscope/staging/metscope; git stash; git pull; npm install;'

  deploy-to-production-env:
    docker:
      - image: circleci/node:10.0
    steps:
      - run:
          name: Ident
          command: |
            echo 'Deploying 'master' branch to production environment'
            ssh -o "StrictHostKeyChecking no" ${DROPLET_USER}@${DROPLET_ADDRESS} '\
            cd /home/metscope/prod/metscope; \
            git pull; \
            docker stop METSCOPE-PROD; \
            docker rm METSCOPE-PROD; \
            docker-compose run --name METSCOPE-PROD --service-ports -d web; \
            echo "Deploy completed"'

workflows:
  version: 2
  BUILD-AND-DEPLOY:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - develop
                - staging
                - master

      - deploy-to-staging-env:
          requires:
            - run-tests
          filters:
            branches:
              only: staging

      - deploy-to-production-env:
          requires:
            - run-tests
          filters:
            branches:
              only: master
